Update to PHPUnit 11
wmde/PsrLogTestDoubles pull request #17
Opened 2024-06-24 13:32 UTC by Sperling-0

- Allow checking in composer.lock files for library repos

Ticket: https://phabricator.wikimedia.org/T359146
Ticket: https://phabricator.wikimedia.org/T359971

2024-08-20 12:40 UTC, gbirke commented
This PR depends on #18 because PHPUnit 11 requires PHP 8.2 as the minmum version. #18 changes the "version matrix" for CI to test only with newer PHP versions.

2025-02-25 16:11 UTC, gbirke commented
I've created #21 to move this PR forward. Please rebase this after merging #21 to check if PHPUnit 11 works ok.

2025-03-03 09:32 UTC, Sperling-0 commented
> rebased main
> 
> this might need a composer.lock file update

`Composer-lock` file updated

2025-04-23 13:20 UTC, moiikana commented
fixing the stuck PI pipeline with https://github.com/wmde/PsrLogTestDoubles/pull/26

2025-04-23 13:22 UTC, moiikana commented on composer.json
>  			"email": "jeroendedauw@gmail.com",
what's the reason for removing WMDE but keeping Jeroen even though this is a repo under the `wmde` namespace on gitlab?

2025-04-23 13:42 UTC, gbirke requested changes
There are some changes that undo things that are already established in `main` (probably because this branch is so old and `main` had some changes that this got mixed up in the rebase). I've marked them, please undo them

2025-04-23 13:42 UTC, gbirke commented on .gitignore
> -composer.lock
Please undo this

2025-04-23 13:42 UTC, gbirke commented on composer.json
> -		},
Please undo this

2025-04-23 13:42 UTC, gbirke commented on composer.json
> +		"psr/log": "~3.0|~2.0"
Please undo this

2025-04-23 15:16 UTC, Sperling-0 commented on .gitignore
> -composer.lock
In past we decided to track 'composer.lock' file, right?

2025-04-23 16:20 UTC, gbirke commented on .gitignore
> -composer.lock
Right, I was confused. Yes, we decided to track it in https://phabricator.wikimedia.org/T359146 where we forgot to list this repo and I mistook this line for deciding to *not* track it, sorry. We keep this change and thanks for asking!

2025-04-23 16:20 UTC, gbirke approved these changes

2025-04-24 07:47 UTC, merged